Iterate by subtracting wavelength
disorderedmaterials/GudPy pull request #24
Opened 2021-07-30 13:06 UTC by jswift-stfc

- PurgeFile class added, which we can run purge_det from.
- WavelengthSubtractionIterator class added, for iteratively subtracting wavelengths.
- Tests added and updated.

Closes #23, #22.

2021-07-30 14:14 UTC, trisyoungs requested changes
Looking good.  Some small suggestions for design changes in the comments.

One general point: I'd like to see more comments in the code - in the present context I'm thinking mainly about your `PurgeFile` `__init__`.  I can follow exactly what you're doing, but a few lines here and there briefly describing blocks of operation would be useful for anyone coming in to look at the code as more of an outsider.

2021-07-30 14:14 UTC, trisyoungs commented on gudrun_classes/wavelength_subtraction_iterator.py
> +        )
In the interests of clarity I think that your `XScaleRangeStep` member should be split into the individual components (e.g. `XMin`, `XMax`, `XStep`) with a flag controlling the use of logarithmic binning.

2021-07-30 14:14 UTC, trisyoungs commented on gudrun_classes/wavelength_subtraction_iterator.py
> +        self.gudrunFile.instrument.scaleSelection = 3
Similarly, an enumeration (which can then map to the integer values) would make the intent of the scale much clearer.

2021-07-30 14:21 UTC, jswift-stfc commented on gudrun_classes/wavelength_subtraction_iterator.py
> +        )
Yes, I think this makes sense.

2021-07-30 14:23 UTC, jswift-stfc commented
> Looking good. Some small suggestions for design changes in the comments.
> 
> One general point: I'd like to see more comments in the code - in the present context I'm thinking mainly about your `PurgeFile` `__init__`. I can follow exactly what you're doing, but a few lines here and there briefly describing blocks of operation would be useful for anyone coming in to look at the code as more of an outsider.

Yes, you are right. Particularly this file is lacking proper documentation. I think I got a bit carried away!

2021-07-30 14:25 UTC, jswift-stfc commented
Not sure what happened exactly with the pipeline. The tests failed claiming that "runThisSample" is not a member of "Sample", yet it is. This was added in this PR. Any idea how to resolve @trisyoungs?

2021-07-30 14:41 UTC, trisyoungs commented
Something to do with line 504 in `tests/test_gudpy_io.py` where you pop the `runThisSample` property?

2021-07-30 14:48 UTC, jswift-stfc commented
> Something to do with line 504 in `tests/test_gudpy_io.py` where you pop the `runThisSample` property?

Oops.. silly mistake. I assumed it was some GitHub concurrency issue. However, it's because I popped the property from a shallow copy of the dictionary.. Thank you!

2021-08-03 08:30 UTC, trisyoungs approved these changes
Couple of small comments - nothing big!

2021-08-03 08:30 UTC, trisyoungs commented on tests/test_gudpy_io.py
> +            "analyse": True,
Perhaps `include` instead?

2021-08-03 08:30 UTC, trisyoungs commented on gudrun_classes/gudrun_file.py
> +            "XMin": "x-scale",
Not sure what this key is for?

2021-08-03 08:39 UTC, jswift-stfc commented on tests/test_gudpy_io.py
> +            "analyse": True,
That seems reasonable!

2021-08-03 08:41 UTC, jswift-stfc commented on gudrun_classes/gudrun_file.py
> +            "XMin": "x-scale",
This key is used to "find" the line with the XMin, XMax, XStep values on.  Since they are always on the same line, I found it easier to use XMin as a key, and then extract the XMax and XStep values from the line that XMin was found on.

2021-08-03 09:20 UTC, jswift-stfc commented
Will also close #25.

2021-08-03 09:26 UTC, merged