Rubber band zoom fix
disorderedmaterials/GudPy pull request #276
Opened 2022-01-10 11:33 UTC by jswift-stfc

Initial fix for the rubber band zooming, to allow it to scale both axes. Closes #153.

2022-01-10 16:44 UTC, trisyoungs requested changes
Unfortunately, while the mechanism works, the area zoomed to doesn't represent that bounded visually by the rubberband.

If I draw a rectangle from x1,y1, to x2,y2 I notice that:
- The larger/higher value of y1 and y2 becomes the new maximum y limit of the graph, but the lower limit is "something else" (I haven't quite managed to work out what, but it certainly isn't the lower value of y1,y2.
- Similarly, the larger of x1,x2 becomes the *lower* limit of the zoomed region - the upper value again doesn't reflect the other of the two values.

2022-01-11 10:13 UTC, jswift-stfc commented
I think I have fixed this, or made it better at least. Now I simply create a QRect: `QRect(x1, y1, x2-x1, y2-y1)` and normalise it, and then use the built-in zoom functionality, to zoom in on this region (this does not set the limits of the graph to that of the rect, but rather centers the rect and scales it, in a sense). Is this functionality okay?

2022-01-12 09:22 UTC, trisyoungs commented
Current behaviour seems to be the same as before (in my previous comment)!

2022-01-12 09:58 UTC, jswift-stfc commented on src/gui/widgets/gudpy_charts.py
> +            left = min([self.rubberBandOrigin.y(), self.rubberBandEnd.y()])
Yes, this was a mistake in the original version. The new version constructs the `QRect` to zoom into as such:

```
# Collect dims for rubber band rect.
width = event.pos().x() - self.rubberBandOrigin.x()
height = event.pos().y() - self.rubberBandOrigin.y()

# Create QRect area to zoom in on.
zoomArea = QRect(
    self.rubberBandOrigin.x(),
    self.rubberBandOrigin.y(),
    width,
    height
).normalized()
```
Where `rubberBandOrigin` is the position of the initial mouse click event.

2022-01-12 10:30 UTC, jswift-stfc commented
> Current behaviour seems to be the same as before (in my previous comment)!

https://user-images.githubusercontent.com/87013792/149123331-42ffe1ec-f043-40f4-8eca-8aa1a7bc8835.mov


Is this the type of behaviour you see?

2022-01-12 11:21 UTC, trisyoungs commented
Hmmm. Obviously a mix-up in downloaded artifacts somehow (or an old PR webpage).  Zoom does work correctly!

2022-01-12 11:22 UTC, trisyoungs approved these changes

2022-01-12 11:26 UTC, jswift-stfc commented
Hurrah!

2022-01-12 12:59 UTC, merged