Further cleanup of the codebase.
disorderedmaterials/GudPy pull request #35
Opened 2021-08-06 16:51 UTC by jswift-stfc

- Fixed a couple of bugs, particularly the ones regarding merge weights and units of density.
- Split some attributes which were stored as tuples of floats into individual attributes.
- Added script specifically for storing enumerators.
- Enumerator for units of density.
- Renamed some attributes to be more meaningful/descriptive.
- Updated testing suites to reflect the above changes.

Closes #28 #29 #30 #31 #33.

N.B. there are further changes that I still want to make, particularly splitting up more tuples of floats into individual attributes and enumerating where possible. However, I think two smaller PR's is better than one large one.

2021-08-06 16:58 UTC, jswift-stfc commented
Forgot to rebase from main for our Windows CI..

2021-08-06 17:52 UTC, trisyoungs requested changes
:+1:, and kepping the enums in a separate file is a sensible way to go.

Almost all of my comments relate to using / comparing your new enums by `type.member.value` when, since we only need to convert to integers when writing out / reading in, readability in the code looks better to me when just using `type.member`, and using `.value` when needing to write an integer value for the benefit of `gudrun_dcs`.

2021-08-06 17:52 UTC, trisyoungs commented on gudrun_classes/container.py
> +        self.densityUnits = 0
Since we're now using an enum here, I would prefer to see this as:
```suggestion
        self.densityUnits = UnitsOfDensity.ATOMIC
```

2021-08-06 17:52 UTC, trisyoungs commented on gudrun_classes/container.py
> +            density = self.density*-1
Such a small suggestion, but why not:
```suggestion
            density = -self.density
```

2021-08-06 17:52 UTC, trisyoungs commented on gudrun_classes/enums.py
> +    D_SPACE = 2
We would commonly refer to this as
```suggestion
    D_SPACING = 2
```

2021-08-06 17:52 UTC, trisyoungs commented on gudrun_classes/gud_file.py
>          Number density of sample (g/cm^3).
```suggestion
        Chemical density of sample (g/cm^3).
```
"Number density" === "atomic density"

2021-08-06 17:52 UTC, trisyoungs commented on gudrun_classes/gudrun_file.py
> +                    container.densityUnits = UnitsOfDensity.CHEMICAL.value
Presumably these can be written without the `.value`?

2021-08-06 17:52 UTC, trisyoungs commented on gudrun_classes/instrument.py
> +            mergeBy = "By channel?"
Again, the `.value` seems unnecessary here - could just store the enum member to aid readability and then write out with `.value`.

2021-08-06 17:52 UTC, trisyoungs commented on gudrun_classes/normalisation.py
> +        self.densityUnits = 0
```suggestion
        self.densityUnits = UnitsOfDensity.ATOMIC
```

2021-08-06 17:52 UTC, trisyoungs commented on gudrun_classes/normalisation.py
> +            density = self.density
More `.value`.

2021-08-06 17:52 UTC, trisyoungs commented on gudrun_classes/sample.py
> +        self.densityUnits = 0
Assign enum member.

2021-08-06 17:52 UTC, trisyoungs commented on gudrun_classes/sample.py
> +            density = self.density
`.value`

2021-08-06 17:52 UTC, trisyoungs commented on gudrun_classes/wavelength_subtraction_iterator.py
> +            Scales.WAVELENGTH.value
Here and below would read a lot more nicely without the `.value`!

2021-08-06 17:53 UTC, trisyoungs commented
Does this need a rebase first?

2021-08-06 18:23 UTC, jswift-stfc commented on gudrun_classes/gudrun_file.py
> +                    container.densityUnits = UnitsOfDensity.CHEMICAL.value
Yes, you're right. When writing out we just need to append .value.

2021-08-06 18:24 UTC, jswift-stfc commented on gudrun_classes/sample.py
> +        self.densityUnits = 0
> Does this need a rebase first?

Yes it does, I'll sort that out alongside the other issues before merging!

2021-08-06 18:50 UTC, jswift-stfc commented
Also need to fix bug introduced in Sample, which is causing the tests to fail.

2021-08-08 17:12 UTC, jswift-stfc commented
Closes #36.
Also closing #34 and #32, I decided not to implement these

2021-08-09 09:23 UTC, trisyoungs approved these changes
Just one minor correction to add to this PR, and two things to consider going forward.

2021-08-09 09:23 UTC, trisyoungs commented on gudrun_classes/instrument.py
> +        self.mergeWeights = MergeWeights.NONE
Thinking ahead to "What should the defaults in the new GUI be?" this would be better intialised to `CHANNEL`.

2021-08-09 09:23 UTC, trisyoungs commented on tests/test_gudpy_io.py
> +                j -= 1
For this, and other code like it, can we add some comments to indicate what logic is being applied?

2021-08-09 09:25 UTC, jswift-stfc commented on gudrun_classes/container.py
> +    density : str
Yeah... I noticed I did this somewhere else and fixed it, thanks for spotting this one!

2021-08-09 09:27 UTC, jswift-stfc commented on gudrun_classes/instrument.py
> +        self.mergeWeights = MergeWeights.NONE
I agree, this is something that we should start to consider. Is this something we can discuss at some point?

2021-08-09 09:29 UTC, jswift-stfc commented on tests/test_gudpy_io.py
> +                j -= 1
Most certainly... Probably should have done this already!

2021-08-09 09:51 UTC, merged