Fix broken X-Scale (2)
disorderedmaterials/GudPy pull request #401
Opened 2022-11-07 11:54 UTC by TerriLouise

2022-11-11 12:31 UTC, TerriLouise reviewed
Second commit to fix previously introduced linting error

2022-11-14 16:58 UTC, TerriLouise commented
When loading YAML input files, X-scale parameters read in correctly.

2022-11-18 14:50 UTC, trisyoungs commented
From Jared's original PR (#396) for posterity:

I believe the issue outlined in https://github.com/disorderedmaterials/GudPy/issues/382 was related to two different issues:
- Changing the XMin never worked, due to a typo.
- Switching between scales was being handled incorrectly leading to incorrectly saving values.
This wasn't noticed, in this case, when saving to a text file because that stores the XStep as -0.01 when logarithmic binning is checked.

2022-11-18 14:52 UTC, trisyoungs requested changes
Some small changes to absorb before merging.

2022-11-18 14:52 UTC, trisyoungs commented on gudpy/gui/widgets/slots/instrument_slots.py
> +                    self.instrument.Xmin,
```suggestion
                    self.instrument.XMin,
```

2022-11-18 14:52 UTC, trisyoungs commented on gudpy/gui/widgets/slots/instrument_slots.py
> +                    self.instrument.Xmin,
```suggestion
                    self.instrument.XMin,
```

2022-11-18 14:52 UTC, trisyoungs commented on gudpy/gui/widgets/slots/instrument_slots.py
> +                    self.instrument.Xmin,
```suggestion
                    self.instrument.XMin,
```

2022-11-18 14:52 UTC, trisyoungs commented on gudpy/gui/widgets/slots/instrument_slots.py
> +                    self.instrument.Xmin,
```suggestion
                    self.instrument.XMin,
```

2022-11-18 15:47 UTC, merged