Prototype GUI
disorderedmaterials/GudPy pull request #75
Opened 2021-09-15 16:11 UTC by jswift-stfc

Okay.. I think it is time for this monster PR to be opened again.

- Basic GUI structure
- GUI is functional.
- An input file can be loaded, altered, purged, viewed and run.
- UI files are being used for the core of the GUI design.
- Some custom widgets have been implemented e.g. `InstrumentWidget`, `BeamWidget`, etc.
- ModelView architecture is being implemented - and custom `QAbstractTableModels`, `QItemDelegates `and `QTableViews` have been implemented. These can be found in `src/gui/widgets/gudpy_tables.py`.
- Some bug fixes throughout the whole project.

Closes #40.

2021-09-17 08:56 UTC, trisyoungs requested changes
Couple of comments on the code itself.  I'll go through the UI files visually in the meantime.

2021-09-17 08:56 UTC, trisyoungs commented on src/gui/widgets/beam_widget.py
> +            self.handleTopScatteredBeamEdgeChanged
From a maintainability perspective, it might be beneficial to have comments that at least indicate the "group" of controls that are being set up, and delimit them from the next.  There is a lot here!

2021-09-17 08:56 UTC, trisyoungs commented on src/gui/widgets/gudpy_tree.py
> +        """
Unless I'm misunderstanding the purpose of this implementation (perhaps it's handled differently in Python vs C++) but this seems to go against the purpose of Qt's MV system in the sense that it is explicitly creating `QStandardItems` for entries in the tree, whereas one would typically have a `QAbstractItemModel` that operated on the `GudrunFile` object...

2021-09-17 08:56 UTC, trisyoungs commented on src/gui/widgets/instrument_widget.py
> +    def initComponents(self):
Again, bit of commenting to break up the swathe of set-up code would be nice here.

2021-09-17 08:56 UTC, trisyoungs commented on src/gui/widgets/main_window.py
> +                        self.objectStack.addWidget(containerWidget)
So here you create a page in your `QStackedWidget` for the beam, instrument, normalisation, and then each individual sample background and sample. This is fine in principle, but is rather wasteful in terms of the sheer number of widgets required to represent the entire input file.  Since only one sample (background) is visible at any given time, one could have single instances of `SampleWidget` and `SampleBackgroundWidget` in the stack. When the active sample (background) changes in your QTreeView you can pass the relevant object to the relevant widget so it can update, and also edit, the data.

2021-09-17 08:56 UTC, trisyoungs commented on src/gui/widgets/normalisation_widget.py
> +    def initComponents(self):
Comments to break up code.

2021-09-17 08:56 UTC, trisyoungs commented on src/gui/widgets/sample_widget.py
> +    def initComponents(self):
Bit of commenting.

2021-09-17 11:03 UTC, jswift-stfc commented on src/gui/widgets/gudpy_tree.py
> +        """
I think that you're right, and this does go against it. I will create a model that inherits `QAbstractItemModel` and operates on the `GudrunFile` object. At the time, I hadn't fully understood MV architecture yet - however now... I understand it a little bit! 😄

2021-09-20 10:28 UTC, trisyoungs approved these changes

2021-09-20 10:30 UTC, merged