Normalisation widget
disorderedmaterials/GudPy pull request #97
Opened 2021-09-24 14:05 UTC by jswift-stfc

Improved the aesthetics of the NormalisationWidget.

- Stopped setting size constraints on widgets.
- More incremental approach to layouts.
- Generally looks better.
- Haven't addressed the issue with using `QPushButtons` over `QToolButtons` for now, since I'd like to address this is it's own PR. (Possibly a PR alongside #90?)

Closes #80.

2021-09-24 14:29 UTC, trisyoungs reviewed
Initial comments:

1. Looks like there's an isolated icon on the "Remove" button in the Data Files group - moving all buttons to this, and converting to `QToolButton` will fixup the layouts a lot too, but this could be a separate general PR.
2. The geometry-related stuff should go into a group a la the Container page, and look consistent w.r.t that. To that end I would be tempted to add a sub-group `Thickness` to hold the upstream /downstream (horizontally).

2021-09-24 14:32 UTC, trisyoungs commented
Also, I think that the "Total Cross Section Source` option can be included at the bottom of the composition group(s).

2021-09-27 09:39 UTC, trisyoungs requested changes
Layout looking good.  One small required addition is the ability to actually choose a "Differential cross section file" - currently the associated "Browse" button does nothing!

2021-09-27 12:30 UTC, trisyoungs approved these changes
One question about checking for the empty string, then good to go.

2021-09-27 12:30 UTC, trisyoungs commented on src/gui/widgets/normalisation_widget.py
> +            self.differentialCrossSectionFileLineEdit.setText(filename[0])
Is there a nicer check for the existence of a filename? In C++ I would use `if (!filename.isEmpty())` since the `getOpenFileName` method returns an empty `QString` if the dialog is cancelled.

2021-09-27 13:04 UTC, jswift-stfc commented on src/gui/widgets/normalisation_widget.py
> +            self.differentialCrossSectionFileLineEdit.setText(filename[0])
Another option could be `if not filename[0] == ""` or `if bool(filename[0])`. General accepted practice for presence check on strings is using `if string`/`if not string`, since empty sequences (strings, in this case) evaluate to false.
I should clarify, that PyQt5 returns `(filename, filter)` from `getOpenFileName` - so `filename[0]` refers to the filename, not the first character in the filename.
I could do something like this:
```
filename, _  = QFileDialog.getOpenFileName(self, "Normalisation differential cross section file", "")
if filename:
     ...
```
Here the filter which is returned is discarded, so the `filename` variable holds ONLY the name of the file.

2021-09-27 13:09 UTC, jswift-stfc commented on src/gui/widgets/normalisation_widget.py
> +            self.differentialCrossSectionFileLineEdit.setText(filename[0])
If the dialog is cancelled, in PyQt5, a tuple of two empty strings is returned.

2021-09-27 13:23 UTC, trisyoungs commented on src/gui/widgets/normalisation_widget.py
> +            self.differentialCrossSectionFileLineEdit.setText(filename[0])
I think I would go for the explicit capture of the filename from the tuple - that makes things absolutely clear.

2021-09-27 13:26 UTC, jswift-stfc commented on src/gui/widgets/normalisation_widget.py
> +            self.differentialCrossSectionFileLineEdit.setText(filename[0])
Got it - I created a new branch `fix-browsing-files`, which I will address this in.

2021-09-27 13:26 UTC, merged